# Configurations
title:            Learn Data Pilipinas
longtitle:        Learn Data Pilipinas
author:           Data Engineering Pilipinas
email:            dataengineeringpilipinas@gmail.com
description: >
  **Learn Data Pilipinas** is an online reference hub for learning data and related skills. We promote open access by providing free, high-quality resources, structured learning paths, and practical tutorials designed to simplify complex topics. Our content incorporates culturally relevant examples to empower Filipino learners and aspiring data professionals.

version:          1.0
gitbook_version:  3.2.3

url:              'https://learndata.ph'
baseurl:          '/'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - pages
  - others

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji


external_links:
  - label: "The Puso Project"
    url: "https://www.thepusoproject.ph/"
  - label: "Data Engineering Pilipinas"
    url: "https://dataengineering.ph/"